######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 25 19:04:58 2007
######################################################################

TEMPLATE = subdirs

CONFIG += ordered

SUBDIRS = \
    src \
    examples
