######################################################################
# Automatically generated by qmake (2.01a) Fr Mai 25 19:04:58 2007
######################################################################

TEMPLATE = app
INCLUDEPATH += . ../../
LIBS += ../../libmaia.a

TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += xml network
QT -= gui
CONFIG += qt silent debug

# Input
HEADERS += client.h
SOURCES += client.cpp client_main.cpp
